import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Car Brochure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1536px] mx-auto">{children}</div>
      </body>
    </html>
  );
}
